# An url presets file used from scripts/istreams.py

1:
    name:   RNE
    url:    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-rne.mp3.m3u

2:
    name:   Radio Clasica 
    url :    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-radioclasica.mp3.m3u

3: 
    name:   Radio 3
    url:    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-radio3.mp3.m3u

4:
    name:   M80          
    url:    http://playerservices.streamtheworld.com/api/livestream-redirect/M80RADIO_SC

5:
    name:   Los 40        
    url:    http://19073.live.streamtheworld.com:3690/LOS40AAC_SC

6:
    name:   Europa FM     
    url:    http://212.129.60.86:9968/stream/1/

