analog:
    gain: 0.0
    in_ports:
        - system:capture_1
        - system:capture_2
    resampled: False
    xo: none

spotify:
    gain: 0
    in_ports:
        - alsa_loop:output_1
        - alsa_loop:output_2
    resampled: False
    xo: none

mpd:
    gain: 0
    in_ports:
        - mpd_loop:output_1
        - mpd_loop:output_2
    resampled: False
    xo: none

net:
    gain: 0
    in_ports:
        - net:from_slave_1
        - net:from_slave_2
    resampled: False
    xo: none

tdt:
    gain: 0
    in_ports:
        - dvb_loop:output_1
        - dvb_loop:output_2
    resampled: False
    xo: none

istreams:
    gain: 0
    in_ports:
        - istreams_loop:output_1
        - istreams_loop:output_2
    resampled: False
    xo: none

