# Clients configuration

# Client start/stop scripts listed in this file are launched on start and stop.
# Names refer to any kind of executable and corresponding options, if any.
# Beware of python executable in case of using a virtual python environement

# mpd:
#     start:  /home/predic/pre.di.c/.venv/bin/python /home/predic/pre.di.c/clients/mpd/mpd_start.py
#     stop:   /home/predic/pre.di.c/.venv/bin/python /home/predic/pre.di.c/clients/mpd/mpd_stop.py
# 
# DVB:
#     start:  /home/predic/pre.di.c/.venv/bin/python /home/predic/pre.di.c/clients/DVB/DVB_start.py
#     stop:   /home/predic/pre.di.c/.venv/bin/python /home/predic/pre.di.c/clients/DVB/DVB_stop.py
# 
# netjack:
#     start:  /home/predic/pre.di.c/clients/netjack_load

#stream_loop:
#    start:  /home/predic/pre.di.c/clients/stream_loop.py

# zita-cd:
#     start:  zita-a2j -d hw:CARD=U24XL,DEV=0 -p 2048 -r 44100 -j cd -v
#     stop:   killall zita-a2j
# 
# librespot:
#     start:  /home/predic/pre.di.c/clients/librespot start
#     stop:   /home/predic/pre.di.c/clients/librespot stop
